#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mumble
Version  : 1.2.19
Release  : 1
URL      : https://github.com/mumble-voip/mumble/releases/download/1.2.19/mumble-1.2.19.tar.gz
Source0  : https://github.com/mumble-voip/mumble/releases/download/1.2.19/mumble-1.2.19.tar.gz
Summary  : Speexdsp is a speech processing library that goes along with the Speex codec
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
BuildRequires : boost-dev
BuildRequires : buildreq-qmake
BuildRequires : mesa-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5Sql)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Xml)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(fftw3f)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(sndfile)
BuildRequires : pkgconfig(x11)
BuildRequires : protobuf
BuildRequires : qttools-dev
BuildRequires : speex-dev
BuildRequires : speexdsp-dev

%description
M U M B L E
A voicechat utility for gamers
http://mumble.info/
#mumble on freenode

%prep
%setup -q -n mumble-1.2.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
%qmake CONFIG+="c++11 bundled-celt no-bundled-opus no-bundled-speex no-g15 no-xevie no-server \ \
no-embed-qt-translations no-update packaged \ \
no-oss no-bonjour"
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1539804063
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mumble
cp LICENSE %{buildroot}/usr/share/package-licenses/mumble/LICENSE
cp celt-0.11.0-src/COPYING %{buildroot}/usr/share/package-licenses/mumble/celt-0.11.0-src_COPYING
cp celt-0.7.0-src/COPYING %{buildroot}/usr/share/package-licenses/mumble/celt-0.7.0-src_COPYING
cp opus-src/COPYING %{buildroot}/usr/share/package-licenses/mumble/opus-src_COPYING
cp sbcelt-src/LICENSE %{buildroot}/usr/share/package-licenses/mumble/sbcelt-src_LICENSE
cp speex/COPYING %{buildroot}/usr/share/package-licenses/mumble/speex_COPYING
%make_install

%files
%defattr(-,root,root,-)
