#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5B8CF87BB893449B (mumble-auto-build-2019@mumble.info)
#
Name     : mumble
Version  : 1.3.0
Release  : 5
URL      : https://github.com/mumble-voip/mumble/releases/download/1.3.0/mumble-1.3.0.tar.gz
Source0  : https://github.com/mumble-voip/mumble/releases/download/1.3.0/mumble-1.3.0.tar.gz
Source1 : https://github.com/mumble-voip/mumble/releases/download/1.3.0/mumble-1.3.0.tar.gz.sig
Summary  : CELT is a low-delay audio codec
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 FTL GPL-2.0 IJG ISC LGPL-2.0 LGPL-2.1 Libpng MIT OpenSSL Sleepycat Unlicense Zlib bzip2-1.0.6
Requires: mumble-bin = %{version}-%{release}
Requires: mumble-data = %{version}-%{release}
Requires: mumble-lib = %{version}-%{release}
Requires: mumble-license = %{version}-%{release}
Requires: mumble-man = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-qmake
BuildRequires : libcap-dev
BuildRequires : mesa-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5DBus)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5Sql)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5TextToSpeech)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5Xml)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(fftw3f)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(sndfile)
BuildRequires : pkgconfig(speexdsp)
BuildRequires : pkgconfig(x11)
BuildRequires : protobuf-dev
BuildRequires : qttools-dev
BuildRequires : speex-dev
BuildRequires : speexdsp-dev

%description
M U M B L E
A voice chat utility for gamers
http://mumble.info/
#mumble on freenode

%package bin
Summary: bin components for the mumble package.
Group: Binaries
Requires: mumble-data = %{version}-%{release}
Requires: mumble-license = %{version}-%{release}

%description bin
bin components for the mumble package.


%package data
Summary: data components for the mumble package.
Group: Data

%description data
data components for the mumble package.


%package extras
Summary: extras components for the mumble package.
Group: Default

%description extras
extras components for the mumble package.


%package lib
Summary: lib components for the mumble package.
Group: Libraries
Requires: mumble-data = %{version}-%{release}
Requires: mumble-license = %{version}-%{release}

%description lib
lib components for the mumble package.


%package license
Summary: license components for the mumble package.
Group: Default

%description license
license components for the mumble package.


%package man
Summary: man components for the mumble package.
Group: Default

%description man
man components for the mumble package.


%prep
%setup -q -n mumble-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
%qmake QMAKE_CFLAGS+=-fno-lto QMAKE_CXXFLAGS+=-fno-lto CONFIG+="c++11 no-bundled-opus no-bundled-speex no-g15 no-xevie server no-ice \ \
no-embed-qt-translations no-update packaged \ \
no-speechd no-rnnoise no-oss no-bonjour"
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1568094493
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mumble
cp 3rdPartyLicenses/appimage_runtime_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_appimage_runtime_license.txt
cp 3rdPartyLicenses/avahi_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_avahi_license.txt
cp 3rdPartyLicenses/berkeleydb_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_berkeleydb_license.txt
cp 3rdPartyLicenses/boost_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_boost_license.txt
cp 3rdPartyLicenses/bzip2_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_bzip2_license.txt
cp 3rdPartyLicenses/dbus_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_dbus_license.txt
cp 3rdPartyLicenses/expat_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_expat_license.txt
cp 3rdPartyLicenses/freetype_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_freetype_license.txt
cp 3rdPartyLicenses/glib_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_glib_license.txt
cp 3rdPartyLicenses/harfbuzzng_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_harfbuzzng_license.txt
cp 3rdPartyLicenses/libcap2_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libcap2_license.txt
cp 3rdPartyLicenses/libdaemon_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libdaemon_license.txt
cp 3rdPartyLicenses/libffi_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libffi_license.txt
cp 3rdPartyLicenses/libflac_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libflac_license.txt
cp 3rdPartyLicenses/libfuse_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libfuse_license.txt
cp 3rdPartyLicenses/libjpeg_turbo_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libjpeg_turbo_license.txt
cp 3rdPartyLicenses/libogg_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libogg_license.txt
cp 3rdPartyLicenses/libpng_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libpng_license.txt
cp 3rdPartyLicenses/libsndfile_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libsndfile_license.txt
cp 3rdPartyLicenses/libvorbis_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_libvorbis_license.txt
cp 3rdPartyLicenses/mach_override_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_mach_override_license.txt
cp 3rdPartyLicenses/mariadb_c_connector_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_mariadb_c_connector_license.txt
cp 3rdPartyLicenses/mcpp_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_mcpp_license.txt
cp 3rdPartyLicenses/mdnsresponder_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_mdnsresponder_license.txt
cp 3rdPartyLicenses/mumble-old-license-headers/LICENSE.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_mumble-old-license-headers_LICENSE.txt
cp 3rdPartyLicenses/openssl_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_openssl_license.txt
cp 3rdPartyLicenses/pcre_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_pcre_license.txt
cp 3rdPartyLicenses/protobuf_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_protobuf_license.txt
cp 3rdPartyLicenses/qt_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_qt_license.txt
cp 3rdPartyLicenses/squashfuse_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_squashfuse_license.txt
cp 3rdPartyLicenses/xar_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_xar_license.txt
cp 3rdPartyLicenses/zeroc_ice_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_zeroc_ice_license.txt
cp 3rdPartyLicenses/zlib_license.txt %{buildroot}/usr/share/package-licenses/mumble/3rdPartyLicenses_zlib_license.txt
cp 3rdparty/arc4random-src/LICENSE %{buildroot}/usr/share/package-licenses/mumble/3rdparty_arc4random-src_LICENSE
cp 3rdparty/celt-0.11.0-src/COPYING %{buildroot}/usr/share/package-licenses/mumble/3rdparty_celt-0.11.0-src_COPYING
cp 3rdparty/celt-0.7.0-src/COPYING %{buildroot}/usr/share/package-licenses/mumble/3rdparty_celt-0.7.0-src_COPYING
cp 3rdparty/minhook-src/LICENSE.txt %{buildroot}/usr/share/package-licenses/mumble/3rdparty_minhook-src_LICENSE.txt
cp 3rdparty/opus-src/COPYING %{buildroot}/usr/share/package-licenses/mumble/3rdparty_opus-src_COPYING
cp 3rdparty/qqbonjour-src/LICENSE %{buildroot}/usr/share/package-licenses/mumble/3rdparty_qqbonjour-src_LICENSE
cp 3rdparty/rnnoise-src/COPYING %{buildroot}/usr/share/package-licenses/mumble/3rdparty_rnnoise-src_COPYING
cp 3rdparty/sbcelt-src/LICENSE %{buildroot}/usr/share/package-licenses/mumble/3rdparty_sbcelt-src_LICENSE
cp 3rdparty/sbcelt-src/celt-0.7.0/COPYING %{buildroot}/usr/share/package-licenses/mumble/3rdparty_sbcelt-src_celt-0.7.0_COPYING
cp 3rdparty/smallft-src/LICENSE %{buildroot}/usr/share/package-licenses/mumble/3rdparty_smallft-src_LICENSE
cp 3rdparty/speex-src/COPYING %{buildroot}/usr/share/package-licenses/mumble/3rdparty_speex-src_COPYING
cp 3rdparty/speexdsp-src/COPYING %{buildroot}/usr/share/package-licenses/mumble/3rdparty_speexdsp-src_COPYING
cp 3rdparty/xinputcheck-src/COPYING.txt %{buildroot}/usr/share/package-licenses/mumble/3rdparty_xinputcheck-src_COPYING.txt
cp LICENSE %{buildroot}/usr/share/package-licenses/mumble/LICENSE
cp icons/flags/LICENSE.md %{buildroot}/usr/share/package-licenses/mumble/icons_flags_LICENSE.md
cp installer/gpl.txt %{buildroot}/usr/share/package-licenses/mumble/installer_gpl.txt
cp src/licenses.h %{buildroot}/usr/share/package-licenses/mumble/src_licenses.h
cp src/mumble/qttranslations/LICENSE %{buildroot}/usr/share/package-licenses/mumble/src_mumble_qttranslations_LICENSE
cp themes/Mumble/LICENSE %{buildroot}/usr/share/package-licenses/mumble/themes_Mumble_LICENSE
%make_install
## install_append content
mkdir -p %{buildroot}/usr/bin
install -m0755 release/mumble scripts/mumble-overlay %{buildroot}/usr/bin/
install -m0755 release/murmurd scripts/mumble-overlay %{buildroot}/usr/bin/
mkdir -p %{buildroot}/usr/share/applications
install -m0644 scripts/mumble.desktop %{buildroot}/usr/share/applications/
mkdir -p %{buildroot}/usr/share/icons/hicolor/scalable/apps
install -m0644 icons/mumble.svg %{buildroot}/usr/share/icons/hicolor/scalable/apps/mumble.svg
mkdir -p %{buildroot}/usr/lib64/mumble
install -m0755 release/libmumble.so.1.3.0 %{buildroot}/usr/lib64/mumble/
ln -sf libmumble.so.1.3.0 %{buildroot}/usr/lib64/mumble/libmumble.so.1.3
ln -sf libmumble.so.1.3.0 %{buildroot}/usr/lib64/mumble/libmumble.so.1
ln -sf libmumble.so.1.3.0 %{buildroot}/usr/lib64/mumble/libmumble.so
install -m0755 release/plugins/liblink.so %{buildroot}/usr/lib64/mumble/
install -m0755 release/plugins/libl4d2.so %{buildroot}/usr/lib64/mumble/
install -m0755 release/plugins/librl.so %{buildroot}/usr/lib64/mumble/
install -m0755 release/libcelt* %{buildroot}/usr/lib64/mumble/
mkdir -p %{buildroot}/usr/share/man/man1
install -m0644 man/mum* %{buildroot}/usr/share/man/man1/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mumble
/usr/bin/mumble-overlay

%files data
%defattr(-,root,root,-)
/usr/share/applications/mumble.desktop
/usr/share/icons/hicolor/scalable/apps/mumble.svg

%files extras
%defattr(-,root,root,-)
/usr/bin/murmurd

%files lib
%defattr(-,root,root,-)
/usr/lib64/mumble/libcelt0.so
/usr/lib64/mumble/libcelt0.so.0
/usr/lib64/mumble/libcelt0.so.0.11
/usr/lib64/mumble/libcelt0.so.0.11.0
/usr/lib64/mumble/libcelt0.so.0.7
/usr/lib64/mumble/libcelt0.so.0.7.0
/usr/lib64/mumble/libl4d2.so
/usr/lib64/mumble/liblink.so
/usr/lib64/mumble/libmumble.so
/usr/lib64/mumble/libmumble.so.1
/usr/lib64/mumble/libmumble.so.1.3
/usr/lib64/mumble/libmumble.so.1.3.0
/usr/lib64/mumble/librl.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mumble/3rdPartyLicenses_appimage_runtime_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_avahi_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_berkeleydb_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_boost_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_bzip2_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_dbus_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_expat_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_freetype_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_glib_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_harfbuzzng_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libcap2_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libdaemon_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libffi_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libflac_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libfuse_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libjpeg_turbo_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libogg_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libpng_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libsndfile_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_libvorbis_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_mach_override_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_mariadb_c_connector_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_mcpp_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_mdnsresponder_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_mumble-old-license-headers_LICENSE.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_openssl_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_pcre_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_protobuf_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_qt_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_squashfuse_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_xar_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_zeroc_ice_license.txt
/usr/share/package-licenses/mumble/3rdPartyLicenses_zlib_license.txt
/usr/share/package-licenses/mumble/3rdparty_arc4random-src_LICENSE
/usr/share/package-licenses/mumble/3rdparty_celt-0.11.0-src_COPYING
/usr/share/package-licenses/mumble/3rdparty_celt-0.7.0-src_COPYING
/usr/share/package-licenses/mumble/3rdparty_minhook-src_LICENSE.txt
/usr/share/package-licenses/mumble/3rdparty_opus-src_COPYING
/usr/share/package-licenses/mumble/3rdparty_qqbonjour-src_LICENSE
/usr/share/package-licenses/mumble/3rdparty_rnnoise-src_COPYING
/usr/share/package-licenses/mumble/3rdparty_sbcelt-src_LICENSE
/usr/share/package-licenses/mumble/3rdparty_sbcelt-src_celt-0.7.0_COPYING
/usr/share/package-licenses/mumble/3rdparty_smallft-src_LICENSE
/usr/share/package-licenses/mumble/3rdparty_speex-src_COPYING
/usr/share/package-licenses/mumble/3rdparty_speexdsp-src_COPYING
/usr/share/package-licenses/mumble/3rdparty_xinputcheck-src_COPYING.txt
/usr/share/package-licenses/mumble/LICENSE
/usr/share/package-licenses/mumble/icons_flags_LICENSE.md
/usr/share/package-licenses/mumble/installer_gpl.txt
/usr/share/package-licenses/mumble/src_licenses.h
/usr/share/package-licenses/mumble/src_mumble_qttranslations_LICENSE
/usr/share/package-licenses/mumble/themes_Mumble_LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mumble-overlay.1
/usr/share/man/man1/mumble.1
